### ISSUE TITLE
Affiliation bug with large Biom

### ISSUE THREAD

**Issue by fescudie** [geraldinepascal/FROGS#15]
Affiliation_OTU raise an exception with a large Biom (96468 clusters and lot of multi-affiliations).
Affiliation_OTU version: 0.9.0
The exception:

```
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/galaxy-dev/galaxy-dist/tools/FROGS/tools/affiliation_OTU.py", line 367, in <module>
    summarise_results( args.summary, args.output_biom, args.taxonomy_ranks )
  File "/usr/local/bioinfo/src/galaxy-dev/galaxy-dist/tools/FROGS/tools/affiliation_OTU.py", line 196, in summarise_results
    global_results, samples_results = get_results( biom_file )
  File "/usr/local/bioinfo/src/galaxy-dev/galaxy-dist/tools/FROGS/tools/affiliation_OTU.py", line 228, in get_results
    biom = BiomIO.from_json( biom_file )
  File "/usr/local/bioinfo/src/galaxy-dev/galaxy-dist/tools/FROGS/bin/biom.py", line 1072, in from_json
    python_dict = json.load( json_data )
  File "/usr/local/bioinfo/src/python/current/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/local/bioinfo/src/python/current/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/local/bioinfo/src/python/current/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 29343485 column -2755604356 - line 66823697 column 2 (char -1539362929 - 2755604367)
```

**Comment by fescudie** [comment]
The problem comes from the core library JSON: http://bugs.python.org/issue16586, http://bugs.python.org/issue10182
When the JSON is parsed the character position is stored with a Long integer (maximal value: 2^31). In the reported case the file contains 2.6G: the number of characters is superior than the position system limit.

**Comment by fescudie** [comment]
To reduce the probability of this problem we have implemented 2 modification in FROGS:
- Reduce the number of characters in pretty print BIOM: 4 spaces for indentation become 2 spaces.
- Use the mono-line format in default outputs.

Enhancements in biom.py v0.11.0 (see commits https://github.com/geraldinepascal/FROGS/commit/28036591870849ade28bfa5b8b58ea38b4738190 and https://github.com/geraldinepascal/FROGS/commit/a958fb404459650c1e7dfc3987d7d8fe95bfaaf7)

**Comment by fescudie** [comment]
The fix has been merged in master branch.
