### ISSUE TITLE
Error in read_biom(biom_file = BIOMfilename) 

### ISSUE THREAD

**Issue by najouamghazli** [geraldinepascal/FROGS#59]
Hi Maria,

I am encountring a problem while trying to run the r_import_data.py. Bellow are the details:
`(base) najoua@LAPTOP-NK0EB027:/mnt/e/Travail_Najoua_2021_2022/Odile$ /home/najoua/FROGS-3.1.0/app/r_import_data.py --biomfile 07-affiliation_Silva.biom --samplefile CompasMetadata.txt --treefile 13-tree-pynast.nwk --rdata 14-phylo_import.Rdata --html 14-phylo_import.html --log-file 14-phylo_import.log`

This gives this error

> Traceback (most recent call last):
>   File "/home/najoua/FROGS-3.1.0/app/r_import_data.py", line 161, in <module>
>     Rscript(biomfile, samplefile, treefile, html, str(args.normalization).upper(), data, ranks, rmd_stderr).submit(args.log_file)
>   File "/home/najoua/FROGS-3.1.0/lib/frogsUtils.py", line 141, in submit
>     subprocess.check_output( self.get_cmd(), shell=True )
>   File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command 'Rscript -e "rmarkdown::render('/home/najoua/FROGS-3.1.0/app/r_import_data.Rmd',output_file='/mnt/e/Travail_Najoua_2021_2022/Odile/14-phylo_import.html', params=list(biomfile='/mnt/e/Travail_Najoua_2021_2022/Odile/1654630328.4_83_07-affiliation_Silva.stdBiom', samplefile='/mnt/e/Travail_Najoua_2021_2022/Odile/CompasMetadata.txt', treefile='/mnt/e/Travail_Najoua_2021_2022/Odile/13-tree-pynast.nwk', normalization=FALSE, outputRdata='/mnt/e/Travail_Najoua_2021_2022/Odile/14-phylo_import.Rdata', ranks='Kingdom Phylum Class Order Family Genus Species', libdir ='/home/najoua/FROGS-3.1.0/lib/external-lib'), intermediates_dir='/mnt/e/Travail_Najoua_2021_2022/Odile')" 2> /mnt/e/Travail_Najoua_2021_2022/Odile/1654630328.4_83_rmarkdown.stderr' returned non-zero exit status 1

When I run the Command 
`Rscript -e "rmarkdown::render('/home/najoua/FROGS-3.1.0/app/r_import_data.Rmd',output_file='/mnt/e/Travail_Najoua_2021_2022/Odile/14-phylo_import.html', params=list(biomfile='/mnt/e/Travail_Najoua_2021_2022/Odile/1654630328.4_83_07-affiliation_Silva.stdBiom', samplefile='/mnt/e/Travail_Najoua_2021_2022/Odile/CompasMetadata.txt', treefile='/mnt/e/Travail_Najoua_2021_2022/Odile/13-tree-pynast.nwk', normalization=FALSE, outputRdata='/mnt/e/Travail_Najoua_2021_2022/Odile/14-phylo_import.Rdata', ranks='Kingdom Phylum Class Order Family Genus Species', libdir ='/home/najoua/FROGS-3.1.0/lib/external-lib'), intermediates_dir='/mnt/e/Travail_Najoua_2021_2022/Odile')" 2> /mnt/e/Travail_Najoua_2021_2022/Odile/1654630328.4_83_rmarkdown.stderr`

I get this in the 1654630328.4_83_rmarkdown.stderr file: 

> processing file: r_import_data.Rmd
> Quitting from lines 57-101 (r_import_data.Rmd) 
> Error in read_biom(biom_file = BIOMfilename) : 
>   Both attempts to read input file:
> /mnt/e/Travail_Najoua_2021_2022/Odile/1654630328.4_83_07-affiliation_Silva.stdBiom
> either as JSON (BIOM-v1) or HDF5 (BIOM-v2).
> Check file path, file name, file itself, then try again.
> Calls: <Anonymous> ... withVisible -> eval -> eval -> import_biom -> read_biom
> Execution halted

I am using FROGS-3.1.0 in Windows Subsystem Linux and also in a Server through putty, and in both cases I get the exact same error.

Could you please guide me in order to resolve this issue ?

Najoua

**Comment by mariabernard** [comment]
Hi Najoua,

Apparently, something going on with the initial biom file ... Could you please share your three input files so I can check contents and reproduce the error?

regards

Maria

**Comment by najouamghazli** [comment]
I sent them via e-mail, thank you.

Best regards,

Najoua
