### ISSUE TITLE
Error while preprocessing 

### ISSUE THREAD

**Issue by pyrosilesl97** [geraldinepascal/FROGS#65]
I got an error when I tried to preprocess my own data using preprocess. 
I have tried to use a gz file with all the *_R1.fastq.gz files and each of them in pairs, but I got the same error. 
The code I used:
`preprocess.py illumina --input-R1 AC1MD1SS08_16S_R1.fastq.gz --input-R2 AC1MD1SS08_16S_R2.fastq.gz --min-amplicon-size 200 --max-amplicon-size 350 --merge-software pear --without-primers --R1-size 300 --R2-size 300 --nb-cpus 5 --output-dereplicated FROGS/preprocess.fasta --output-count FROGS/preprocess.tsv --summary FROGS/preprocess.html --log-file FROGS/preprocess.log`

The output: 

`Traceback (most recent call last):
  File "/media/strain/datos/AaronDavid/Anaconda3/envs/frogs@4.0.1/bin/preprocess.py", line 1292, in <module>
    process( args )
  File "/media/strain/datos/AaronDavid/Anaconda3/envs/frogs@4.0.1/bin/preprocess.py", line 1098, in process
    filter_process_multiples_files( R1_files, R2_files, samples_names, filtered_files, art_filtered_files, lengths_files, log_files, args )
  File "/media/strain/datos/AaronDavid/Anaconda3/envs/frogs@4.0.1/bin/preprocess.py", line 902, in filter_process_multiples_files
    process_sample( R1_files[idx], R2_files[idx], samples_names[idx], out_files[idx], out_art_files[idx], lengths_files[idx], log_files[idx], args )
  File "/media/strain/datos/AaronDavid/Anaconda3/envs/frogs@4.0.1/bin/preprocess.py", line 1003, in process_sample
    pear_cmd.submit(log_file)
  File "/media/strain/datos/AaronDavid/Anaconda3/envs/frogs@4.0.1/lib/frogsUtils.py", line 151, in submit
    FH_log.write( '# ' + self.description + ' (' + os.path.basename(self.program) + ' version : ' + self.get_version() + ')\n' )
  File "/media/strain/datos/AaronDavid/Anaconda3/envs/frogs@4.0.1/bin/preprocess.py", line 87, in get_version
    return Cmd.get_version(self, 'stdout').split()[1].strip()
IndexError: list index out of range`

When I run the test 
`sh test_frogs.sh <NB_CPU> <JAVA_MEM> <OUT_FOLDER>` 
everything seems ok.

**Comment by mariabernard** [comment]
Dear Pablo,

I saw that you want to use Pear as read pair merging tool. As Pear is under licence for private users, we were not allowed to include it in the frogs_conda_requirement. 
If you want to use Pear (and respect their licence), you need to add it in the frogs@4.0.1 conda environment 
The following command should work.
```
conda activate frogs@4.0.1
conda install -c bioconda pear
```

For your information, when a tool crashed you may rerun the command line with --debug option. This will keep temporary files and logs and allow you to rerun individual command line wrapped in the FROGS tools. This could help understanding why the tools did'nt work.

Regards

Maria

**Comment by pyrosilesl97** [comment]
Dear Maria, 

Thank you very much for your response. I will make the adjustment you mention before running frogs. 

Regards, 
Pablo
