### ISSUE TITLE
Difficulty Installing and Running FROGS Workflow v5

### ISSUE THREAD

**Issue by CaroleBelliardo** [geraldinepascal/FROGS#72]
Hi @geraldinepascal, 

I’m excited to use the FROGS workflow v5, but I’ve encountered several issues during installation and running the workflow on my laptop (local machine) and a SLURM server using Singularity. I would appreciate your help in resolving them.
1. Conda Installation Issue:

When following the instructions from your GitHub repository for installing FROGS v5 via Conda:
```conda env create --name frogs@5.0.0 --file frogs-conda-requirements.yaml```

I consistently receive the following error message related to package incompatibilities:

```.... ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libgfortran4-7.5.0-h14aa051_20, conda-forge/linux-64::libgfortran5-14.1.0-hc5f4f2c_1
  path: 'share/licenses/libgfortran/RUNTIME.LIBRARY.EXCEPTION

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::perl-compress-raw-bzip2-2.087-pl526he1b5a44_0, bioconda/linux-64::perl-extutils-makemaker-7.36-pl526_1, bioconda/linux-64::perl-io-zlib-1.10-pl526_2, bioconda/linux-64::perl-perlio-gzip-0.20-pl526h84994c4_1, bioconda/linux-64::perl-json-4.02-pl526_0
  path: 'lib/5.26.2/x86_64-linux-thread-multi/perllocal.pod```

I’ve tried multiple approaches, but nothing has resolved this conflict. Could you please provide any guidance or suggest a workaround?
2. Singularity Execution Issue:
I also tried using the Singularity image from [Galaxy Depot](https://depot.galaxyproject.org/singularity/) and faced the following error when running the denoising step:

```Traceback (most recent call last):
  File "/usr/local/bin/denoising.py", line 2246, in <module>
    process( args )
  File "/usr/local/bin/denoising.py", line 1992, in process
    merge_primers_filters_multiple_files( R1_files, R2_files, samples_names, filtered_files, art_filtered_files, lengths_files, log_files, args )
  File "/usr/local/bin/denoising.py", line 1585, in merge_primers_filters_multiple_files
    merge_primers_filters(R1_files[idx], R2_files[idx], samples_names[idx], out_files[idx], out_art_files[idx], lengths_files[idx], log_files[idx], args )
  File "/usr/local/bin/denoising.py", line 1678, in merge_primers_filters
    vsearch_cmd.submit(log_file)
  File "/usr/local/lib/frogsUtils.py", line 156, in submit
    subprocess.check_output( self.get_cmd(), shell=True )
  File "/usr/local/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'vsearch  --threads 1 --fastq_mergepairs /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/metabarcoding/1_dataori/Mistic_salad_V1-V2_S183_R1_001.fastq.gz --reverse /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/metabarcoding/1_dataori/Mistic_salad_V1-V2_S183_R2_001.fastq.gz --fastqout /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/metabarcoding/1_dataori/../2_preprocessing/1725377198.108454_990751_Mistic_salad_V1-V2_S183_R1_001_vsearch.assembled.fastq  --fastqout_notmerged_fwd /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/metabarcoding/1_dataori/../2_preprocessing/1725377198.108454_990751_Mistic_salad_V1-V2_S183_R1_001_vsearch.unassembled_R1.fastq  --fastqout_notmerged_rev /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/metabarcoding/1_dataori/../2_preprocessing/1725377198.108454_990751_Mistic_salad_V1-V2_S183_R1_001_vsearch.unassembled_R2.fastq  --fastq_allowmergestagger --fastq_ascii 33 --fastq_maxdiffpct 10.0 --fastq_minovlen 10 2> /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/metabarcoding/1_dataori/../2_preprocessing/1725377198.108454_990751_Mistic_salad_V1-V2_S183_R1_001_vsearch.log' returned non-zero exit status 127.```

It seems related to the ```vsearch``` command returning a non-zero exit status. I have the same issue using Flash. Both tools seem not to be installed inside Singularity due to incompatibility in the Python version. 

Any assistance you can provide on these issues would be greatly appreciated!

Many thanks for considering my request.

Best regards,
Carole

**Comment by olivierrue** [comment]
Hi Carole,
sorry for the late reply. I tried again to install FROGS 5.0.0 and asked for the installation on a bioinformatics platform. Both installations worked with `conda`.
Here are a few suggestions:
- update your conda version
- try `mamba` instead of `conda` (some conflicts are better handled)
- try remove `lib/5.26.2/x86_64-linux-thread-multi/perllocal.pod` and install FROGS again

I hope you'll manage to install the tool

Best regard,
Olivier

**Comment by LabeoFD** [comment]
Hi @olivierrue,

I faced also many issues during installation and running the FROGS workflow v5  on my local machine (Mac M3). Is there a way to get FROGS workflow v5 running on Mac M3?
I tried with `conda` and with `mamba` but I couldn't make it work.
I followed the instructions from [the GitHub repository](https://github.com/geraldinepascal/FROGS) for installing FROGS v5 via Conda:
`conda env create --name frogs@5.0.0 --file frogs-conda-requirements.yaml`
I get this error message:
`Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - unsupported request
  - unsupported request
  - unsupported request
  - unsupported request
  - unsupported request
  - unsupported request
  - unsupported request
  - unsupported request
  - unsupported request
  - nothing provides bioconductor-biobase >=2.54.0,<2.55.0 needed by bioconductor-phyloseq-1.38.0-r41hdfd78af_0
  - unsupported request
  - unsupported request
  - package flash-1.2.11-h57f5043_1 requires libzlib >=1.3.1,<2.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ bioconductor-dada2 =1.22.0 * does not exist (perhaps a typo or a missing channel);
├─ bioconductor-deseq2 =1.34.0 * does not exist (perhaps a typo or a missing channel);
├─ bioconductor-phyloseq =1.38 * is not installable because it requires
│  └─ bioconductor-biobase >=2.54.0,<2.55.0 *, which does not exist (perhaps a missing channel);
├─ blast =2.10 * does not exist (perhaps a typo or a missing channel);
├─ cutadapt =2.10 * does not exist (perhaps a typo or a missing channel);
├─ emboss =6.6.0 * does not exist (perhaps a typo or a missing channel);
├─ fasttree =2.1.9 * does not exist (perhaps a typo or a missing channel);
├─ flash =1.2.11 * is installable and it requires
│  └─ libzlib >=1.3.1,<2.0a0 * with the potential options
│     ├─ libzlib 1.3.1 would require
│     │  └─ zlib ==1.3.1 *_0, which can be installed;
│     ├─ libzlib 1.3.1 would require
│     │  └─ zlib ==1.3.1 *_2, which can be installed;
│     └─ libzlib 1.3.1 would require
│        └─ zlib ==1.3.1 *_1, which can be installed;
├─ frogs =5.0.0 * does not exist (perhaps a typo or a missing channel);
├─ mafft =7.407 * does not exist (perhaps a typo or a missing channel);
├─ r-base =4.1.2 * is not installable because it requires
│  ├─ cairo >=1.16.0,<2.0.0a0 * with the potential options
│  │  ├─ cairo 1.16.0 would require
│  │  │  └─ icu >=72.1,<73.0a0 *, which can be installed;
│  │  ├─ cairo [1.16.0|1.18.0] would require
│  │  │  └─ icu >=73.2,<74.0a0 *, which can be installed;
│  │  ├─ cairo [1.18.0|1.18.2] would require
│  │  │  └─ icu >=75.1,<76.0a0 *, which can be installed;
│  │  ├─ cairo 1.16.0 would require
│  │  │  └─ icu >=68.1,<69.0a0 *, which can be installed;
│  │  ├─ cairo 1.16.0 would require
│  │  │  └─ icu >=70.1,<71.0a0 *, which can be installed;
│  │  ├─ cairo 1.16.0 would require
│  │  │  └─ icu >=67.1,<68.0a0 *, which can be installed;
│  │  ├─ cairo 1.16.0 would require
│  │  │  └─ zlib >=1.2.11,<1.3.0a0 *, which conflicts with any installable versions previously reported;
│  │  ├─ cairo 1.16.0 would require
│  │  │  └─ zlib >=1.2.12,<1.3.0a0 *, which conflicts with any installable versions previously reported;
│  │  └─ cairo 1.16.0 would require
│  │     └─ zlib >=1.2.13,<1.3.0a0 *, which conflicts with any installable versions previously reported;
│  └─ icu >=69.1,<70.0a0 *, which conflicts with any installable versions previously reported;
├─ r-phangorn =2.7.0 * does not exist (perhaps a typo or a missing channel);
├─ swarm =3.1.4 * does not exist (perhaps a typo or a missing channel);
└─ vsearch =2.17.0 * does not exist (perhaps a typo or a missing channel).`

**Comment by olivierrue** [comment]
Hi @LabeoFD
the installation has not been designed for osx-arm64 architectures.
At present, not all FROGS dependencies are compatible with osx-arm64 architectures.
For example, version 2.17 of vsearch, which we request, is not available:

```
conda search vsearch --platform osx-arm64
Loading channels: done
# Name                       Version           Build  Channel             
vsearch                       2.28.1      he5cb1a1_1  bioconda            
vsearch                       2.29.0      he5cb1a1_0  bioconda            
vsearch                       2.29.1      he5cb1a1_0  bioconda            
vsearch                       2.29.1      hf8bb5b5_1  bioconda            
vsearch                       2.29.2      hf8bb5b5_0  bioconda            
vsearch                       2.29.2      hf8bb5b5_1  bioconda   

```

We will see if we can fix it but it requires a lot of tests to check.
